// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Kimmoonsu/directconnect-api/internal/protocols"
	"github.com/Kimmoonsu/directconnect-api/internal/protocols/router"
	"github.com/Kimmoonsu/directconnect-api/src/handlers"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitHttpProtocol() *protocols.HttpImpl {
	httpHandlerImpl := handlers.NewHttpHandler()
	httpRouterImpl := router.NewHttpRoute(httpHandlerImpl)
	httpImpl := protocols.NewHttpProtocol(httpRouterImpl)
	return httpImpl
}

// wire.go:

// Wiring for http protocol
var httpHandler = wire.NewSet(handlers.NewHttpHandler)

// Wiring protocol routing
var httpRouter = wire.NewSet(router.NewHttpRoute)
